export const toolImages: Record<string, string> = {
  "Balance": "https://files.meilleurduchef.com/mdc/photo/produit/hen/balance-cuisine-15kg/balance-cuisine-15kg-1-cat-320.jpg",
  "Batteur électrique": "https://files.meilleurduchef.com/mdc/photo/produit/wil/batteur-probaker-noir/batteur-probaker-noir-1-cat-320.jpg",
  "Casserole": "https://files.meilleurduchef.com/mdc/photo/produit/mfr/casserole-excellence-20/casserole-excellence-20-1-cat-320.jpg",
  "Cercle à tarte": "https://files.meilleurduchef.com/mdc/photo/produit/gob/cercle-tarte-inox-perfore-18-ht-2/cercle-tarte-inox-perfore-18-ht-2-1-cat-320.jpg",
  "Chalumeau": "https://files.meilleurduchef.com/mdc/photo/produit/mfr/chalumeau-gaz-pro-cuisine/chalumeau-gaz-pro-cuisine-1-cat-320.jpg",
  "Chinois": "https://files.meilleurduchef.com/mdc/photo/produit/mfr/passe-sauce-exoglass/passe-sauce-exoglass-1-cat-320.jpg",
  "Corne à ramasser": "https://files.meilleurduchef.com/mdc/photo/produit/mto/corne-francaise-rigide/corne-francaise-rigide-1-cat-320.jpg",
  "Couteau": "https://files.meilleurduchef.com/mdc/photo/produit/deg/couteau-cuisine-20/couteau-cuisine-20-1-cat-320.jpg",
  "Couteau de chef": "https://images.unsplash.com/photo-1606859191214-2581b4a65e956?auto=format&fit=crop&w=800&q=80",
  "Cul-de-poule": "https://files.meilleurduchef.com/mdc/photo/produit/mfr/cul-poule-25cm/cul-poule-25cm-1-cat-320.jpg",
  "Fer à caraméliser": "https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?auto=format&fit=crop&w=800&q=80",
  "Film alimentaire": "https://files.meilleurduchef.com/mdc/photo/produit/flo/film-etirable-alimentaire/film-etirable-alimentaire-1-cat-320.jpg",
  "Fouet": "https://files.meilleurduchef.com/mdc/photo/produit/mfe/fouet-cuisine/fouet-cuisine-1-zoom.jpg",
  "Fourchette": "https://files.meilleurduchef.com/mdc/photo/produit/mfr/fourchette-diapason/fourchette-diapason-1-cat-320.jpg",
  "Louche": "https://files.meilleurduchef.com/mdc/photo/produit/mfr/louche-monobloc-7/louche-monobloc-7-1-cat-320.jpg",
  "Maryse": "https://files.meilleurduchef.com/mdc/photo/produit/deg/maryse-silicone-25cm/maryse-silicone-25cm-1-cat-320.jpg",
  "Mixeur": "https://files.meilleurduchef.com/mdc/photo/produit/mfr/mixeur-plongeant-junior-225/mixeur-plongeant-junior-225-1-cat-320.jpg",
  "Mixeur plongeant": "https://files.meilleurduchef.com/mdc/photo/produit/emi/mixeur-bamix-m160-one-blanc/mixeur-bamix-m160-one-blanc-1-zoom.jpg",
  "Moule à brioche": "https://files.meilleurduchef.com/mdc/photo/produit/mfr/moule-brioche-exopan-10/moule-brioche-exopan-10-1-cat-320.jpg",
  "Moule à cake": "https://files.meilleurduchef.com/mdc/photo/produit/mfe/moule-cake-fer-blanc-12/moule-cake-fer-blanc-12-1-cat-320.jpg",
  "Moule à financiers": "https://files.meilleurduchef.com/mdc/photo/produit/mfr/moule-financier-exoglass/moule-financier-exoglass-1-cat-320.jpg",
  "Moule à flan": "https://files.meilleurduchef.com/mdc/photo/produit/mfr/moule-manque-exoglass/moule-manque-exoglass-1-cat-320.jpg",
  "Moule à madeleines": "https://files.meilleurduchef.com/mdc/photo/produit/mfr/plaque-12-madeleines-exopan/plaque-12-madeleines-exopan-1-cat-320.jpg",
  "Moule à manqué": "https://files.meilleurduchef.com/mdc/photo/produit/mfr/moule-manque-exoglass/moule-manque-exoglass-1-cat-320.jpg",
  "Moules individuels": "https://files.meilleurduchef.com/mdc/photo/produit/mfr/petit-four-tartelette-cannele-exopan/petit-four-tartelette-cannele-exopan-1-cat-320.jpg",
  "Pinceau": "https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=800&q=80",
  "Plaque": "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
  "Plaque de cuisson": "https://files.meilleurduchef.com/mdc/photo/produit/mfr/plaque-patisserie-aluminium-perforee/plaque-patisserie-aluminium-perforee-1-cat-320.jpg",
  "Plat à four": "https://files.meilleurduchef.com/mdc/photo/produit/lac/plat-four-inox-35-26/plat-four-inox-35-26-1-cat-320.jpg",
  "Poche à douille": "https://files.meilleurduchef.com/mdc/photo/produit/mfr/poches-douille-jetables-standard-51-26/poches-douille-jetables-standard-51-26-1-cat-320.jpg",
  "Poêle à crêpes": "https://files.meilleurduchef.com/mdc/photo/produit/deb/poele-crepes-acier-20/poele-crepes-acier-20-1-cat-320.jpg",
  "Presse-agrume": "https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?auto=format&fit=crop&w=800&q=80",
  "Ramequins": "https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?auto=format&fit=crop&w=800&q=80",
  "Robot pâtissier": "https://files.meilleurduchef.com/mdc/photo/produit/mfr/batteur-alphamix-2-5/batteur-alphamix-2-5-1-cat-320.jpg",
  "Rouleau à pâtisserie": "https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?auto=format&fit=crop&w=800&q=80",
  "Sonde thermique": "https://files.meilleurduchef.com/mdc/photo/produit/all/thermometre-digital-etanche/thermometre-digital-etanche-1-zoom.jpg",
  "Spatule": "https://files.meilleurduchef.com/mdc/photo/produit/mfr/spatule-exoglass-30/spatule-exoglass-30-1-cat-320.jpg",
  "Spatule coudée": "https://files.meilleurduchef.com/mdc/photo/produit/arc/mini-spatule/mini-spatule-1-cat-320.jpg",
  "Spatule Exoglass": "https://files.meilleurduchef.com/mdc/photo/produit/mfr/spatule-exoglass-30/spatule-exoglass-30-1-cat-320.jpg",
  "Tamis": "https://files.meilleurduchef.com/mdc/photo/produit/mfr/tamis-inox-20-maille-08/tamis-inox-20-maille-08-1-cat-320.jpg",
  "Zesteur": "https://files.meilleurduchef.com/mdc/photo/produit/mfr/zesteur-microplane-premium-noir/zesteur-microplane-premium-noir-1-cat-320.jpg",
}

export function getToolImage(name: string): string | undefined {
  return toolImages[name]
}
